default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: shaadi_matching_development

test:
  <<: *default
  database: shaadi_matching_test

production:
  <<: *default
  database: <%= ENV['DATABASE_URL'] %>
  url: <%= ENV['DATABASE_URL'] %>

